// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Recordings V1 API 0.2.13

export interface Recording { "id"?: string; "audio_path"?: string | null; "raw_text"?: string; "processed_text"?: string | null; "processing_mode"?: "raw" | "enhanced"; "model_used"?: string; "enhancement_model"?: string | null; "duration_ms"?: number; "language"?: string | null; "tags"?: Array<string>; "agent_id"?: string | null; "project_id"?: string | null; "session_id"?: string | null; "goal"?: string | null; "role"?: string | null; "task_list_id"?: string | null; "machine_id"?: string | null; "metadata"?: Record<string, unknown>; "created_at"?: string }

export interface Agent { "id"?: string; "name"?: string; "description"?: string | null; "role"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "last_seen_at"?: string }

export interface Project { "id"?: string; "name"?: string; "path"?: string; "description"?: string | null; "created_at"?: string; "updated_at"?: string }

export interface CreateRecordingInput { "id"?: string; "raw_text": string; "audio_path"?: string; "processed_text"?: string; "processing_mode"?: "raw" | "enhanced"; "model_used"?: string; "enhancement_model"?: string; "duration_ms"?: number; "language"?: string; "tags"?: Array<string>; "agent_id"?: string; "project_id"?: string; "session_id"?: string; "goal"?: string; "role"?: string; "task_list_id"?: string; "machine_id"?: string; "metadata"?: Record<string, unknown> }

export interface RegisterAgentInput { "name": string; "description"?: string; "role"?: string }

export interface RegisterProjectInput { "name": string; "path": string; "description"?: string }

export interface RecordingsV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class RecordingsV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: RecordingsV1ClientOptions) {
    if (!options.baseUrl) throw new Error("RecordingsV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (Array.isArray(value)) {
          for (const item of value) url.searchParams.append(key, String(item));
        } else if (value !== undefined && value !== null) {
          url.searchParams.set(key, String(value));
        }
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** List agents */
    async listAgents(init?: RequestInit): Promise<{ "agents"?: Array<Agent>; "count"?: number }> {
      return this.request("GET", `/v1/agents`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Register (upsert) an agent */
    async registerAgent(body: RegisterAgentInput, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("POST", `/v1/agents`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get an agent by id or name */
    async getAgent(id: string, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("GET", `/v1/agents/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List projects */
    async listProjects(init?: RequestInit): Promise<{ "projects"?: Array<Project>; "count"?: number }> {
      return this.request("GET", `/v1/projects`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Register (upsert) a project */
    async registerProject(body: RegisterProjectInput, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("POST", `/v1/projects`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a project by id or path */
    async getProject(id: string, init?: RequestInit): Promise<{ "project"?: Project }> {
      return this.request("GET", `/v1/projects/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List recordings */
    async listRecordings(query?: { "agent_id"?: string; "project_id"?: string; "session_id"?: string; "processing_mode"?: "raw" | "enhanced"; "tags"?: Array<string>; "search"?: string; "since"?: string; "until"?: string; "limit"?: number; "offset"?: number }, init?: RequestInit): Promise<{ "recordings"?: Array<Recording>; "count"?: number }> {
      return this.request("GET", `/v1/recordings`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a recording */
    async createRecording(body: CreateRecordingInput, init?: RequestInit): Promise<{ "recording"?: Recording }> {
      return this.request("POST", `/v1/recordings`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a recording by id */
    async getRecording(id: string, init?: RequestInit): Promise<{ "recording"?: Recording }> {
      return this.request("GET", `/v1/recordings/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a recording by id */
    async deleteRecording(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean }> {
      return this.request("DELETE", `/v1/recordings/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Aggregate recording statistics */
    async getRecordingStats(init?: RequestInit): Promise<{ "total"?: number; "raw"?: number; "enhanced"?: number; "total_duration_ms"?: number; "by_model"?: Record<string, number> }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }
}
