/**
 * Generates the test-literal mutation manifest for the vacuity battery (OPE41-00029).
 *
 * This exists instead of a committed manifest of byte offsets. Offsets are correct for exactly one
 * revision of the test files: the first commit that adds a comment above a converted site shifts
 * every offset below it, and the battery then reports MUTATION-NOT-APPLIED for rows that were fine.
 * That happened — 66 of 176 rows went stale in one commit — and while the driver refuses to score a
 * mutation it could not apply, a stale manifest still costs a full run and reads like a coverage
 * hole. Generating from the current tree removes the failure mode rather than documenting it.
 *
 * For every `expectOrder` / `sliceBetween` / `sliceBetweenUnique` call site it emits one `corrupt`
 * row per string-literal operand: append a sentinel to that literal in the test file, which is
 * equivalent — from the assertion's point of view — to deleting the needle from the source, but
 * needs no map from haystack variable to source path and leaves the script under test byte-identical
 * so the run still succeeds and only the converted assertion can fail.
 *
 * Operands that are `const` variables rather than literals are NOT emitted here; those are covered
 * by the source-side rows in scripts/vacuity-manifests/variable-operands.tsv.
 *
 * Usage: bun scripts/vacuity-manifest-gen.ts > /tmp/corrupt-sites.tsv
 */
import { readFileSync } from "node:fs";
import { Glob } from "bun";

const HELPERS = /\b(expectOrder|sliceBetweenUnique|sliceBetween)\s*\(/g;

/** The nearest enclosing `it(...)` / `test(...)` name, used as the `-t` filter. */
function enclosingTest(source: string, position: number): string | undefined {
  let best: string | undefined;
  const pattern = /\b(?:it|test)\s*\(\s*(["'`])((?:\\.|(?!\1).)*)\1/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(source))) {
    if (match.index >= position) break;
    best = match[2];
  }
  return best;
}

/** Top-level string-literal arguments of a call, as [offset-of-inner-text, raw-inner-text]. */
function literalArguments(source: string, openParen: number): Array<[number, string]> {
  const found: Array<[number, string]> = [];
  let index = openParen + 1;
  let depth = 1;
  while (index < source.length && depth > 0) {
    const character = source[index];
    if (character === "(") depth++;
    else if (character === ")") depth--;
    else if (character === '"' || character === "'" || character === "`") {
      const quote = character;
      const start = ++index;
      while (index < source.length && source[index] !== quote) {
        if (source[index] === "\\") index++;
        index++;
      }
      if (depth === 1) found.push([start, source.slice(start, index)]);
    }
    index++;
  }
  return found;
}

/** TSV cannot carry a real tab or newline. Backslash sequences pass through untouched, because the
 *  mutation compares the file's RAW bytes and `\n` inside a TS literal is two of them. */
function escapeForTsv(text: string): string {
  return text.replace(/\t/g, "\\t").replace(/\n/g, "\\n");
}

const emitted = new Set<string>();
const lines: string[] = [
  "# GENERATED by scripts/vacuity-manifest-gen.ts - do not hand-edit, regenerate.",
  "# kind\ttestFile\ttestName\ttargetFile\toffset\tliteral",
];

for (const path of new Glob("src/**/*.test.ts").scanSync(".")) {
  // The guards suite calls the helpers on hand-built strings to prove they THROW. Its literals are
  // fixtures, not needles into a real source file, so corrupting them measures nothing about the
  // repo and only adds noise to the tally.
  if (path.endsWith("source-assertions-guards.test.ts")) continue;
  const source = readFileSync(path, "utf8");
  HELPERS.lastIndex = 0;
  let call: RegExpExecArray | null;
  while ((call = HELPERS.exec(source))) {
    const testName = enclosingTest(source, call.index);
    if (!testName) continue;
    for (const [offset, raw] of literalArguments(source, call.index + call[0].length - 1).slice(0, 2)) {
      if (raw.length < 3) continue;
      const key = `${path}:${offset}`;
      if (emitted.has(key)) continue;
      emitted.add(key);
      lines.push(`corrupt\t${path}\t${testName}\t${path}\t${offset}\t${escapeForTsv(raw)}`);
    }
  }
}

console.log(lines.join("\n"));
console.error(`generated ${emitted.size} corrupt rows`);
